### ISSUE TITLE
report log scale estimates 

### ISSUE THREAD

**Issue by mebrooks** [nissandjac/smsR#1]
An older version reported estimates of `logCatch`, `logFbar`, and `logSSB` with their estimated standard deviations each year. These are useful for plotting them on the natural scale with CI that reflect that they were estimated on the log-scale. This latest one only has `logRec`

**Comment by nissandjac** [comment]
Thanks Mollie, I've updated the code now so you can both get those from the TMB object and the getX range of functions that get different estimates of catch, biomass, ssb, etc extract the CI from logspace

**Comment by mebrooks** [comment]
Thanks for the update. I looked into getting average F on the log scale and I see that SMS had input `avg_F_ages` to enable this. I also considered doing it on the R side of things, but the calculations are more unpleasant than doing it in C++. So I'd be willing to do the following (with any suggested modifications):
 - change the structure of `df.tmb` to include `avg.F.ages`
 - add code in `sms.cpp` to calculate and ADREPORT `logFbar`
 - change `smsPlots()`, `mohns_rho()` and `sandeel_example.R` to reflect the new structure of `df.tmb`

**Comment by nissandjac** [comment]
Mollie, 
there is an R function that calculates Fbar in smsR - it's called getFbar.

```
Fbar <- getFbar(df.tmb, sas, Fbarage = c(1,2))

```
It is already getting F from the log scale in that function. 

If you would prefer to get it from the .cpp code feel free to add it, and perhaps also change the getFbar function to get the confidence interval directly from tmb.
