### ISSUE TITLE
df.tmb$years not matching other df.tmb objects

### ISSUE THREAD

**Issue by mebrooks** [nissandjac/smsR#12]
I noticed that the objects like `df.tmb$M` and `df.tmb$west` increased their size recently, so that now their 2nd dimension is `1+length(df.tmb$years)`, whereas they used to match. Was this on purpose and will it stay the same, or should `df.tmb$years` get longer as well? I'm asking because it affects the MSE code.

**Comment by nissandjac** [comment]
This was on purpose to help the new forecast functions - the extra year is used to forecast the next year.  

nyears should stay the same, however it will be 1 shorter than the life history parameters, since they include a projected year
